name: Ejecutar Scraper Diario

on:
  schedule:
    - cron: '0 10 * * *'  # Todos los días a las 10:00 UTC (5:00 AM Colombia)
  workflow_dispatch:      # Permite ejecución manual

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias del sistema
        run: sudo apt-get install -y python3-dev build-essential

      - name: Instalar dependencias del proyecto
        run: |
          pip install --upgrade pip
          pip install feedparser beautifulsoup4 requests pandas sentence-transformers scikit-learn openpyxl tqdm notebook ipykernel nbconvert

      - name: Ejecutar notebook
        run: |
          jupyter nbconvert --to notebook --execute prueba2.ipynb --output prueba2_ejecutado.ipynb --ExecutePreprocessor.timeout=600

      - name: Subir archivo Excel generado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización automática de resultados"
          file_pattern: "resultados/*.xlsx"
