name: Ejecutar Scraper Diario

on:
  schedule:
    - cron: '0 10 * * *'   # Todos los días a las 10:00 UTC (5:00 AM Colombia)
  workflow_dispatch:       # Permite ejecutarlo manualmente

jobs:
  ejecutar-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar Jupyter
        run: |
          pip install notebook ipykernel nbconvert

      - name: Ejecutar notebook
        run: |
          jupyter nbconvert --to notebook --execute prueba2.ipynb --output prueba2_ejecutado.ipynb

      - name: Subir resultados al repositorio
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Resultados actualizados automáticamente"
          file_pattern: 'resultados/*.xlsx'
